# ::crseo::AtmosphereBuilder

r0_at_zenith = 0.16
oscale = 25.0
zenith_angle = 0.5235987755982988

[turbulence]
n_layer = 7
altitude = [
    25.0,
    275.0,
    425.0,
    1250.0,
    4000.0,
    8000.0,
    13000.0,
]
xi0 = [
    0.1256999969482422,
    0.08739999681711197,
    0.066600002348423,
    0.3497999906539917,
    0.2273000031709671,
    0.06809999793767929,
    0.07509999722242355,
]
wind_speed = [
    5.6539998054504395,
    5.79640007019043,
    5.894199848175049,
    6.63700008392334,
    13.292499542236328,
    34.82500076293945,
    29.418699264526367,
]
wind_direction = [
    0.01360000018030405,
    0.14409999549388885,
    0.21770000457763672,
    0.5672000050544739,
    1.2583999633789063,
    1.6266000270843506,
    1.7461999654769897,
]

[ray_tracing]
width = 25.5
n_width_px = 865
field_size = 0.002908881986513734
duration = 30.0
filepath = "/home/ubuntu/data/home/ubuntu/projects/gmt-ns-im/atmosphere/atmosphere.bin"
n_duration = 1
